language: dart

dart:
- 2.3.0
- dev

dart_task:
- test: -p vm
- dartanalyzer: --fatal-infos --fatal-warnings .

matrix:
  include:
  - dart: dev
    dart_task: dartfmt

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
  - $HOME/.pub-cache
